spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bilibili
    username: root
    password: 827165648
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-underline: true
